using System.Collections.Generic;
using System.Linq;
using Singularity.Data.Entities;
using Singularity.Engine.Analysis.CueDetr;
using Singularity.Services.AudioAnalysis;
using Xunit;

namespace Singularity.Tests.Engine;

public class CueDetrFusionTests
{
    private const double Bpm = 174, Downbeat = 0.5;
    private static readonly double Bar = 240.0 / Bpm;

    private static List<CuePointEntity> Orbit() => new()
    {
        new() { TimestampInSeconds = Downbeat + 32 * Bar, Label = "Drop 1", Type = CuePointType.Drop, Confidence = 0.6f },
        new() { TimestampInSeconds = Downbeat + 96 * Bar, Label = "Drop 2", Type = CuePointType.Drop, Confidence = 0.6f },
    };

    private static readonly List<CueDetrPoint> Ai = new()
    {
        new(0, Downbeat + 32 * Bar + 0.4, 1.0),   // agrees with Drop 1 (within a bar)
        new(0, Downbeat + 64 * Bar + 0.2, 0.93),  // ORBIT has nothing here
    };

    [Fact]
    public void Compare_MarksAgreement_AndAddsTheOtherAiPointsOnTheBarGrid()
    {
        var cues = CueDetrFusion.Apply(Orbit(), Ai, "h", Bpm, Downbeat, 300, CueSourceMode.Compare);

        Assert.Equal(new[] { "Drop 1 ✓AI", "AI 0.93", "Drop 2" }, cues.Select(c => c.Label));
        Assert.Equal(0.9f, cues[0].Confidence);
        Assert.Equal(0.6f, cues[2].Confidence);
        var ai = cues[1];
        Assert.Equal(Downbeat + 64 * Bar, ai.TimestampInSeconds, 6);   // snapped
        Assert.Equal((CueDetrFusion.AiColour, -1, true), (ai.Color, ai.SlotIndex, ai.IsAutoGenerated));
    }

    [Fact]
    public void AiOnly_ReplacesOrbitsCuesWithSnappedAiPoints()
    {
        var cues = CueDetrFusion.Apply(Orbit(), Ai, "h", Bpm, Downbeat, 300, CueSourceMode.AiOnly);

        Assert.Equal(new[] { "AI 1", "AI 2" }, cues.Select(c => c.Label));
        Assert.Equal(new[] { Downbeat + 32 * Bar, Downbeat + 64 * Bar }, cues.Select(c => c.TimestampInSeconds), new ToleranceComparer());
        Assert.All(cues, c => Assert.Equal("h", c.TrackUniqueHash));
    }

    [Fact]
    public void Orbit_LeavesCuesAlone()
    {
        var cues = CueDetrFusion.Apply(Orbit(), Ai, "h", Bpm, Downbeat, 300, CueSourceMode.Orbit);
        Assert.Equal(new[] { "Drop 1", "Drop 2" }, cues.Select(c => c.Label));
    }

    [Fact]
    public void Cache_RoundTripsAndIsIgnoredForAnotherModel()
    {
        const string json = """{"model":"cue-detr|AAAA","points":[{"t":44.3,"s":0.906},{"t":220.89,"s":1}]}""";

        var points = CueDetrCueService.ReadCache(json, "cue-detr|AAAA");
        Assert.NotNull(points);
        Assert.Equal(new[] { 44.3, 220.89 }, points!.Select(p => p.Seconds));
        Assert.Equal(1908, points[0].Frame);
        Assert.Null(CueDetrCueService.ReadCache(json, "cue-detr|BBBB"));
        Assert.Null(CueDetrCueService.ReadCache(null, "cue-detr|AAAA"));
        Assert.Null(CueDetrCueService.ReadCache("garbage", "cue-detr|AAAA"));
    }

    private sealed class ToleranceComparer : IEqualityComparer<double>
    {
        public bool Equals(double a, double b) => System.Math.Abs(a - b) < 1e-6;
        public int GetHashCode(double d) => 0;
    }
}
