using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SLSKDONET.Migrations
{
    /// <inheritdoc />
    public partial class AddEmbeddingBlobColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "BeatGridJson",
                table: "audio_features",
                type: "TEXT",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<double>(
                name: "DownbeatOffsetSeconds",
                table: "audio_features",
                type: "REAL",
                nullable: false,
                defaultValue: 0.0);

            migrationBuilder.AddColumn<byte[]>(
                name: "EmbeddingBlob",
                table: "audio_features",
                type: "BLOB",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "EmbeddingModelTag",
                table: "audio_features",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<byte[]>(
                name: "WaveformBlob",
                table: "audio_features",
                type: "BLOB",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "WaveformBlobSampleCount",
                table: "audio_features",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "CuePoints",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    TrackUniqueHash = table.Column<string>(type: "TEXT", nullable: false),
                    TimestampInSeconds = table.Column<double>(type: "REAL", nullable: false),
                    Type = table.Column<int>(type: "INTEGER", nullable: false),
                    Label = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false),
                    Color = table.Column<string>(type: "TEXT", maxLength: 7, nullable: false),
                    IsAutoGenerated = table.Column<bool>(type: "INTEGER", nullable: false),
                    Confidence = table.Column<float>(type: "REAL", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CuePoints", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CuePoints_TrackHash_AutoGenerated",
                table: "CuePoints",
                columns: new[] { "TrackUniqueHash", "IsAutoGenerated" });

            migrationBuilder.CreateIndex(
                name: "IX_CuePoints_TrackUniqueHash",
                table: "CuePoints",
                column: "TrackUniqueHash");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CuePoints");

            migrationBuilder.DropColumn(
                name: "BeatGridJson",
                table: "audio_features");

            migrationBuilder.DropColumn(
                name: "DownbeatOffsetSeconds",
                table: "audio_features");

            migrationBuilder.DropColumn(
                name: "EmbeddingBlob",
                table: "audio_features");

            migrationBuilder.DropColumn(
                name: "EmbeddingModelTag",
                table: "audio_features");

            migrationBuilder.DropColumn(
                name: "WaveformBlob",
                table: "audio_features");

            migrationBuilder.DropColumn(
                name: "WaveformBlobSampleCount",
                table: "audio_features");
        }
    }
}
