// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SLSKDONET.Data;

#nullable disable

namespace SLSKDONET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110043711_Phase21_AIBrain_Final")]
    partial class Phase21_AIBrain_Final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SLSKDONET.Data.Entities.AudioAnalysisEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Arousal")
                        .HasColumnType("REAL");

                    b.Property<int>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Danceability")
                        .HasColumnType("REAL");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DynamicRange")
                        .HasColumnType("REAL");

                    b.Property<int>("FrequencyCutoff")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("InstrumentalProbability")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsInstrumental")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUpscaled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LoudnessLufs")
                        .HasColumnType("REAL");

                    b.Property<string>("MusicalStyle")
                        .HasColumnType("TEXT");

                    b.Property<double>("QualityConfidence")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sadness")
                        .HasColumnType("REAL");

                    b.Property<int>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpectralHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackUniqueHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TruePeakDb")
                        .HasColumnType("REAL");

                    b.Property<double?>("Valence")
                        .HasColumnType("REAL");

                    b.Property<string>("VectorEmbeddingJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("audio_analysis");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.AudioFeaturesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiEmbeddingJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalysisVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("Arousal")
                        .HasColumnType("REAL");

                    b.Property<float>("Bpm")
                        .HasColumnType("REAL");

                    b.Property<float>("BpmConfidence")
                        .HasColumnType("REAL");

                    b.Property<float>("BpmStability")
                        .HasColumnType("REAL");

                    b.Property<string>("CamelotKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChordProgression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("CueBuild")
                        .HasColumnType("REAL");

                    b.Property<float?>("CueDrop")
                        .HasColumnType("REAL");

                    b.Property<float>("CueIntro")
                        .HasColumnType("REAL");

                    b.Property<float?>("CuePhraseStart")
                        .HasColumnType("REAL");

                    b.Property<int>("CurationConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Danceability")
                        .HasColumnType("REAL");

                    b.Property<string>("DetectedSubGenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("DropConfidence")
                        .HasColumnType("REAL");

                    b.Property<float?>("DropTimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<float>("DynamicComplexity")
                        .HasColumnType("REAL");

                    b.Property<string>("ElectronicSubgenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("ElectronicSubgenreConfidence")
                        .HasColumnType("REAL");

                    b.Property<float>("EmbeddingMagnitude")
                        .HasColumnType("REAL");

                    b.Property<float>("Energy")
                        .HasColumnType("REAL");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GenreDistributionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("InstrumentalProbability")
                        .HasColumnType("REAL");

                    b.Property<float>("Intensity")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDjTool")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDynamicCompressed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("KeyConfidence")
                        .HasColumnType("REAL");

                    b.Property<float>("LoudnessLUFS")
                        .HasColumnType("REAL");

                    b.Property<float>("MoodConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("MoodTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("OnsetRate")
                        .HasColumnType("REAL");

                    b.Property<string>("PredictedVibe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PredictionConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ProvenanceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("Sadness")
                        .HasColumnType("REAL");

                    b.Property<string>("Scale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SpectralCentroid")
                        .HasColumnType("REAL");

                    b.Property<float>("SpectralComplexity")
                        .HasColumnType("REAL");

                    b.Property<float>("SubGenreConfidence")
                        .HasColumnType("REAL");

                    b.Property<float>("TonalProbability")
                        .HasColumnType("REAL");

                    b.Property<string>("TrackUniqueHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valence")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("VectorEmbeddingBytes")
                        .HasColumnType("BLOB")
                        .HasColumnName("VectorEmbedding");

                    b.HasKey("Id");

                    b.HasIndex("TrackUniqueHash")
                        .IsUnique();

                    b.ToTable("audio_features");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.BlacklistedItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_Blacklist_Hash");

                    b.ToTable("BlacklistedItems");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.EnrichmentTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_EnrichmentTasks_Status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_EnrichmentTasks_Status_CreatedAt");

                    b.ToTable("EnrichmentTasks");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.ForensicLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ForensicLogs");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.GenreCueTemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cue1Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cue1Label")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Cue1OffsetBars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cue1Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cue2Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cue2Label")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Cue2OffsetBars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cue2Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cue3Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cue3Label")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Cue3OffsetBars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cue3Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cue4Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cue4Label")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Cue4OffsetBars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cue4Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cue5Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cue5Label")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Cue5OffsetBars")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cue5Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cue6Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cue6Label")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Cue6OffsetBars")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cue6Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cue7Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cue7Label")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Cue7OffsetBars")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cue7Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cue8Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cue8Label")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Cue8OffsetBars")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cue8Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GenreCueTemplates");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.LibraryActionLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackArtist")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LibraryActionLogs");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.LibraryFolderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TracksFound")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LibraryFolders");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.PendingOrchestrationEntity", b =>
                {
                    b.Property<string>("TrackUniqueHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TrackUniqueHash");

                    b.ToTable("PendingOrchestrations");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.SpotifyMetadataCacheEntity", b =>
                {
                    b.Property<string>("SpotifyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SpotifyId");

                    b.ToTable("SpotifyMetadataCache");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.StyleDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CentroidJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentGenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceTrackHashesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("style_definitions");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.TrackPhraseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<float>("EndTimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<float>("EnergyLevel")
                        .HasColumnType("REAL");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<float>("StartTimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("TrackUniqueHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrackPhrases");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.TrackTechnicalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiEmbeddingJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("CuePointsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurationConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("HighData")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReviewNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("LowData")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("MidData")
                        .HasColumnType("BLOB");

                    b.Property<Guid>("PlaylistTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryGenre")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvenanceJson")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RmsData")
                        .HasColumnType("BLOB");

                    b.Property<string>("SpectralHash")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("WaveformData")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistTrackId")
                        .IsUnique();

                    b.ToTable("TechnicalDetails");
                });

            modelBuilder.Entity("SLSKDONET.Data.LibraryEntryEntity", b =>
                {
                    b.Property<string>("UniqueHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BPM")
                        .HasColumnType("REAL");

                    b.Property<int>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanonicalDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CuePointsJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Danceability")
                        .HasColumnType("REAL");

                    b.Property<string>("DetectedSubGenre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DynamicRange")
                        .HasColumnType("REAL");

                    b.Property<double?>("Energy")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FilePathUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("HighData")
                        .HasColumnType("BLOB");

                    b.Property<string>("ISRC")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InstrumentalProbability")
                        .HasColumnType("REAL");

                    b.Property<int>("Integrity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnriched")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Loudness")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("LowData")
                        .HasColumnType("BLOB");

                    b.Property<double?>("ManualBPM")
                        .HasColumnType("REAL");

                    b.Property<string>("ManualKey")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("MidData")
                        .HasColumnType("BLOB");

                    b.Property<string>("MusicalKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Popularity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryGenre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RmsData")
                        .HasColumnType("BLOB");

                    b.Property<string>("SpotifyAlbumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyArtistId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpotifyBPM")
                        .HasColumnType("REAL");

                    b.Property<string>("SpotifyKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyTrackId")
                        .HasColumnType("TEXT");

                    b.Property<float?>("SubGenreConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TruePeak")
                        .HasColumnType("REAL");

                    b.Property<double?>("Valence")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("WaveformData")
                        .HasColumnType("BLOB");

                    b.HasKey("UniqueHash");

                    b.ToTable("LibraryEntries");
                });

            modelBuilder.Entity("SLSKDONET.Data.LibraryHealthEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BronzeCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FreeStorageBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HqTracks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingUpdates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SilverCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopGenresJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalStorageBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradableCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LibraryHealth");
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistActivityLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSmartPlaylist")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserPaused")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmartCriteriaJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessfulCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PlaylistJob_CreatedAt");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistTrackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AnalysisOffset")
                        .HasColumnType("REAL");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BPM")
                        .HasColumnType("REAL");

                    b.Property<int>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BitrateScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanonicalDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CuePointsJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Danceability")
                        .HasColumnType("REAL");

                    b.Property<string>("DetectedSubGenre")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DynamicRange")
                        .HasColumnType("REAL");

                    b.Property<double?>("Energy")
                        .HasColumnType("REAL");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FrequencyCutoff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISRC")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InstrumentalProbability")
                        .HasColumnType("REAL");

                    b.Property<int>("Integrity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnriched")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsTrustworthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Loudness")
                        .HasColumnType("REAL");

                    b.Property<double?>("ManualBPM")
                        .HasColumnType("REAL");

                    b.Property<string>("ManualKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinBitrateOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MusicalKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Popularity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredFormats")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryGenre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("QualityConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("QualityDetails")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourcePlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePlaylistName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpectralHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyAlbumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyArtistId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpotifyBPM")
                        .HasColumnType("REAL");

                    b.Property<string>("SpotifyKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("SubGenreConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackUniqueHash")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TruePeak")
                        .HasColumnType("REAL");

                    b.Property<double?>("Valence")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId")
                        .HasDatabaseName("IX_PlaylistTrack_PlaylistId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PlaylistTrack_Status");

                    b.HasIndex("TrackUniqueHash");

                    b.ToTable("PlaylistTracks");
                });

            modelBuilder.Entity("SLSKDONET.Data.QueueItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentTrack")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlaylistTrackId")
                        .HasColumnType("TEXT");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("QueueItems");
                });

            modelBuilder.Entity("SLSKDONET.Data.TrackEntity", b =>
                {
                    b.Property<string>("GlobalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AnalysisOffset")
                        .HasColumnType("REAL");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BPM")
                        .HasColumnType("REAL");

                    b.Property<int>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BitrateScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanonicalDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CuePointsJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Danceability")
                        .HasColumnType("REAL");

                    b.Property<string>("DetectedSubGenre")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Energy")
                        .HasColumnType("REAL");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FrequencyCutoff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISRC")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InstrumentalProbability")
                        .HasColumnType("REAL");

                    b.Property<int>("Integrity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnriched")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsTrustworthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpgradeAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpgradeScanAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ManualBPM")
                        .HasColumnType("REAL");

                    b.Property<string>("ManualKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinBitrateOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoodTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicalKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRetryTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Popularity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredFormats")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousBitrate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryGenre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("QualityConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("QualityDetails")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoulseekUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourcePlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePlaylistName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpectralHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyAlbumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyArtistId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpotifyBPM")
                        .HasColumnType("REAL");

                    b.Property<string>("SpotifyKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpgradeSource")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valence")
                        .HasColumnType("REAL");

                    b.HasKey("GlobalId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.AudioFeaturesEntity", b =>
                {
                    b.HasOne("SLSKDONET.Data.LibraryEntryEntity", null)
                        .WithOne("AudioFeatures")
                        .HasForeignKey("SLSKDONET.Data.Entities.AudioFeaturesEntity", "TrackUniqueHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SLSKDONET.Data.Entities.TrackTechnicalEntity", b =>
                {
                    b.HasOne("SLSKDONET.Data.PlaylistTrackEntity", "PlaylistTrack")
                        .WithOne("TechnicalDetails")
                        .HasForeignKey("SLSKDONET.Data.Entities.TrackTechnicalEntity", "PlaylistTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaylistTrack");
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistActivityLogEntity", b =>
                {
                    b.HasOne("SLSKDONET.Data.PlaylistJobEntity", "Job")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistTrackEntity", b =>
                {
                    b.HasOne("SLSKDONET.Data.PlaylistJobEntity", "Job")
                        .WithMany("Tracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SLSKDONET.Data.Entities.AudioFeaturesEntity", "AudioFeatures")
                        .WithMany()
                        .HasForeignKey("TrackUniqueHash")
                        .HasPrincipalKey("TrackUniqueHash");

                    b.Navigation("AudioFeatures");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SLSKDONET.Data.LibraryEntryEntity", b =>
                {
                    b.Navigation("AudioFeatures");
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistJobEntity", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistTrackEntity", b =>
                {
                    b.Navigation("TechnicalDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
