using System;
using System.Collections.Generic;
using System.Linq;
using System.Reactive.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using Singularity.Data.Entities;
using Singularity.Models;
using Singularity.Services;
using Singularity.ViewModels;
using Xunit;

namespace Singularity.Tests.ViewModels;

public class TrackCueEditorViewModelTests
{
    // 120 BPM: beat 0.5 s, bar 2 s, 8-bar phrase 16 s. Downbeat at 1 s.
    private const double Bpm = 120, Downbeat = 1.0, Duration = 300;

    private static (TrackCueEditorViewModel Editor, Mock<ICuePointService> Service) Build(params CuePointEntity[] stored)
    {
        var service = new Mock<ICuePointService>();
        var editor = new TrackCueEditorViewModel("Outgoing", service.Object, null, NullLogger.Instance);
        editor.Load("hash", "Track", null, Bpm, Downbeat, Duration, stored);
        return (editor, service);
    }

    private static CuePointEntity Stored(double t, string label, int slot = -1, CuePointType type = CuePointType.Drop) => new()
    {
        TrackUniqueHash = "hash", TimestampInSeconds = t, Label = label, SlotIndex = slot, Type = type,
        IsAutoGenerated = true, Color = "#FF0000", Confidence = 0.9f,
    };

    [Fact]
    public void Snap_UsesTheTracksGrid_FromTheDownbeat()
    {
        var (editor, _) = Build();

        editor.SnapMode = CueSnapMode.Bar;
        Assert.Equal(5.0, editor.Snap(5.6), 6);   // bars at 1, 3, 5, 7...

        editor.SnapMode = CueSnapMode.Beat;
        Assert.Equal(5.5, editor.Snap(5.6), 6);

        editor.SnapMode = CueSnapMode.Phrase;
        Assert.Equal(17.0, editor.Snap(20.0), 6); // phrases at 1, 17, 33...

        editor.SnapMode = CueSnapMode.Off;
        Assert.Equal(5.6, editor.Snap(5.6), 6);
    }

    [Fact]
    public void AddCue_SnapsTakesTheFirstFreePad_AndMarksDirty()
    {
        var (editor, _) = Build(Stored(10, "Drop", slot: 0));

        editor.AddCueAtCommand.Execute(20.4).Subscribe();

        var added = Assert.Single(editor.Cues, c => c.Name == "Cue 2");
        Assert.Equal(21.0, added.Timestamp, 6);
        Assert.Equal(1, added.SlotIndex); // pad A is taken
        Assert.Equal(CueSource.User, added.Source);
        Assert.Same(added, editor.SelectedCue);
        Assert.True(editor.IsDirty);
    }

    [Fact]
    public void AssigningATakenPad_TurnsItsPreviousOwnerIntoAMemoryCue()
    {
        var (editor, _) = Build(Stored(10, "A", slot: 0), Stored(20, "B", slot: 1));
        editor.SelectedCue = editor.Cues.Single(c => c.Name == "B");

        editor.SelectedSlot = TrackCueEditorViewModel.SlotOptions.Single(o => o.Index == 0);

        Assert.Equal(0, editor.Cues.Single(c => c.Name == "B").SlotIndex);
        Assert.Equal(-1, editor.Cues.Single(c => c.Name == "A").SlotIndex);
    }

    [Fact]
    public void ChangingRole_AppliesItsColour_AndMakesItAUserCue()
    {
        var (editor, _) = Build(Stored(10, "X"));
        editor.SelectedCue = editor.Cues[0];

        editor.SelectedRole = CueRole.Intro;

        Assert.Equal(CueRole.Intro, editor.Cues[0].Role);
        Assert.Equal(CueForgeViewModel.RekordboxColorForRole(CueRole.Intro), editor.Cues[0].Color);
        Assert.Equal(CueSource.User, editor.Cues[0].Source);
    }

    [Fact]
    public void Undo_And_Redo_RestoreEarlierStates()
    {
        var (editor, _) = Build(Stored(10, "Drop"));
        editor.SelectedCue = editor.Cues[0];
        editor.DeleteSelectedCommand.Execute().Subscribe();
        Assert.Empty(editor.Cues);

        editor.UndoCommand.Execute().Subscribe();
        Assert.Single(editor.Cues);
        Assert.Equal("Drop", editor.Cues[0].Name);

        editor.RedoCommand.Execute().Subscribe();
        Assert.Empty(editor.Cues);
    }

    [Fact]
    public void DraggingACue_SnapsIt_AndReportsTheMove()
    {
        var (editor, _) = Build(Stored(11, "Drop"));
        (double From, double To)? moved = null;
        editor.CueMoved += (_, m) => moved = m;

        var cue = editor.Cues[0];
        cue.Timestamp = 14.3; // what the waveform does while dragging
        editor.CueUpdatedCommand.Execute(cue).Subscribe();

        Assert.Equal(15.0, cue.Timestamp, 6);
        Assert.Equal((11.0, 15.0), moved);
        Assert.True(editor.IsDirty);

        editor.UndoCommand.Execute().Subscribe();
        Assert.Equal(11.0, editor.Cues[0].Timestamp, 6);
    }

    [Fact]
    public void NudgingALoop_MovesItsEndToo()
    {
        var (editor, _) = Build(Stored(11, "Drop"));
        editor.SelectedCue = editor.Cues[0];
        editor.SetSelectedLoopBarsCommand.Execute(4).Subscribe();
        Assert.True(editor.Cues[0].IsLoop);
        Assert.Equal(19.0, editor.Cues[0].LoopEndSeconds, 6); // 4 bars = 8 s

        editor.NudgeSelectedCommand.Execute("+bar").Subscribe();

        Assert.Equal(13.0, editor.Cues[0].Timestamp, 6);
        Assert.Equal(21.0, editor.Cues[0].LoopEndSeconds, 6);
    }

    [Fact]
    public async Task Save_ReplacesTheTracksCues_WithTheWorkingSet()
    {
        var (editor, service) = Build(Stored(10, "Drop", slot: 0));
        List<CuePointEntity>? written = null;
        service.Setup(s => s.CreateManyAsync(It.IsAny<IEnumerable<CuePointEntity>>(), It.IsAny<CancellationToken>()))
               .Callback<IEnumerable<CuePointEntity>, CancellationToken>((e, _) => written = e.ToList())
               .Returns(Task.CompletedTask);
        editor.SelectedCue = editor.Cues[0];
        editor.SelectedName = "Big drop";

        Assert.True(await editor.SaveIfDirtyAsync());

        service.Verify(s => s.DeleteAllByTrackIdAsync("hash", It.IsAny<CancellationToken>()), Times.Once);
        var cue = Assert.Single(written!);
        Assert.Equal("Big drop", cue.Label);
        Assert.False(cue.IsAutoGenerated); // edited, so auto-analysis won't overwrite it
        Assert.Equal(0, cue.SlotIndex);
        Assert.False(editor.IsDirty);
        Assert.False(await editor.SaveIfDirtyAsync()); // nothing left to save
    }

    [Fact]
    public void SettingADrop_PlacesCountdowns_MovingItMovesThem_DeletingItRemovesThem()
    {
        var (editor, _) = Build(Stored(81, "Hit", type: CuePointType.PhraseBoundary)); // 120 BPM: bar = 2 s
        editor.InitDropCountdownMode("16,8");
        editor.SelectedCue = editor.Cues.Single();

        editor.SelectedRole = CueRole.Drop;
        // [IN -16] [IN -8] [DROP 1], and [OUT] 32 bars after the drop.
        Assert.Equal(new[] { 49.0, 65.0, 81.0, 145.0 }, editor.Cues.Select(c => c.Timestamp));
        Assert.Equal(new[] { "[IN -16]", "[IN -8]", "[DROP 1]", "[OUT]" }, editor.Cues.Select(c => c.Name));

        editor.NudgeSelectedCommand.Execute("+bar").Subscribe();
        Assert.Equal(new[] { 51.0, 67.0, 83.0, 147.0 }, editor.Cues.Select(c => c.Timestamp));

        editor.DeleteSelectedCommand.Execute().Subscribe();
        Assert.Empty(editor.Cues);
    }

    [Fact]
    public void TemplateOff_PlacesNoBuildIns()
    {
        var (editor, _) = Build(Stored(81, "Hit", type: CuePointType.PhraseBoundary));
        editor.InitDropCountdownMode("Off");
        editor.SelectedCue = editor.Cues.Single();

        editor.SelectedRole = CueRole.Drop;

        Assert.DoesNotContain(editor.Cues, c => c.Role == CueRole.Build);
        Assert.Equal(new[] { "[DROP 1]", "[OUT]" }, editor.Cues.Select(c => c.Name));
    }

    [Fact]
    public void FineNudge_Moves10Ms_WithoutSnapping()
    {
        var (editor, _) = Build(Stored(11, "Drop"));
        editor.SelectedCue = editor.Cues[0];

        editor.NudgeSelectedCommand.Execute("+fine").Subscribe();

        Assert.Equal(11.010, editor.Cues.Single(c => c.Name == "Drop").Timestamp, 6);
    }

    [Fact]
    public void UseAsMixPoint_ReportsTheSelectedCuesTime()
    {
        var (editor, _) = Build(Stored(42, "Outro", type: CuePointType.Outro));
        double? trigger = null;
        editor.TriggerRequested += (_, t) => trigger = t;
        editor.SelectedCue = editor.Cues[0];

        editor.UseSelectedAsTriggerCommand.Execute().Subscribe();

        Assert.Equal(42.0, trigger);
    }

    [Fact]
    public void DropHere_AddsADropOnTheBeat_WithCountdownCuesBeforeIt()
    {
        var (editor, _) = Build();
        editor.LastAuditionSeconds = 65.3;

        editor.SetDropHereCommand.Execute().Subscribe();

        var drop = Assert.Single(editor.Cues, c => c.Role == CueRole.Drop);
        Assert.Equal(("[DROP 1]", 2), (drop.Name, drop.SlotIndex)); // pad C
        Assert.Equal(65.0, drop.Timestamp, 6);                   // snapped to the bar grid
        var countdowns = editor.Cues.Where(c => c.Role == CueRole.Build).ToList();
        Assert.NotEmpty(countdowns);
        Assert.All(countdowns, c => Assert.True(c.Timestamp < drop.Timestamp));
        Assert.True(editor.IsDirty);
    }

    [Fact]
    public void DropHere_TurnsTheCueAlreadyOnThatBeatIntoTheDrop()
    {
        var (editor, _) = Build(Stored(65, "Cue 1", slot: 2, type: CuePointType.PhraseBoundary));
        editor.LastAuditionSeconds = 65.1;

        editor.SetDropHereCommand.Execute().Subscribe();

        var drop = Assert.Single(editor.Cues, c => c.Role == CueRole.Drop);
        Assert.Equal((65.0, 2, "[DROP 1]"), (drop.Timestamp, drop.SlotIndex, drop.Name));
        Assert.DoesNotContain(editor.Cues, c => c.Name == "Cue 1");
    }

    [Fact]
    public async Task GenerateCues_RunsTheGenerator_ReloadsStoredCues_AndTellsTheHost()
    {
        var (editor, service) = Build(Stored(10, "Old"));
        service.Setup(s => s.GetByTrackIdAsync("hash", It.IsAny<CancellationToken>()))
            .ReturnsAsync(new List<CuePointEntity> { Stored(30, "Drop 1 ✓AI"), Stored(50, "AI 0.95", type: CuePointType.PhraseBoundary) });
        Singularity.Engine.Analysis.CueDetr.CueSourceMode? asked = null;
        editor.CueGenerator = (hash, path, mode) => { asked = mode; return Task.FromResult((true, "done")); };
        int changed = 0;
        editor.CuesChanged += (_, _) => changed++;

        await editor.GenerateCuesCommand.Execute("compare");

        Assert.Equal(Singularity.Engine.Analysis.CueDetr.CueSourceMode.Compare, asked);
        Assert.Equal(new[] { "Drop 1 ✓AI", "AI 0.95" }, editor.Cues.Select(c => c.Name));
        Assert.Equal((1, "done", false), (changed, editor.StatusText, editor.IsDirty));
    }

    [Fact]
    public void SettingADropYourself_ClearsTheOtherAutoCues_ButKeepsYours()
    {
        var mine = Stored(41, "My cue", type: CuePointType.PhraseBoundary);
        mine.IsAutoGenerated = false;
        var (editor, _) = Build(Stored(21, "Intro", type: CuePointType.Intro), Stored(101, "Drop 2"), mine);
        editor.LastAuditionSeconds = 65;

        editor.SetDropHereCommand.Execute().Subscribe();

        Assert.DoesNotContain(editor.Cues, c => c.Name is "Intro" or "Drop 2");
        Assert.Contains(editor.Cues, c => c.Name == "My cue");
        Assert.Contains(editor.Cues, c => c.Name == "[DROP 1]" && c.Role == CueRole.Drop);
        Assert.Contains(editor.Cues, c => c.Name.StartsWith("[IN -"));
        Assert.Contains(editor.Cues, c => c.Name == "[OUT]");

        editor.UndoCommand.Execute().Subscribe();
        Assert.Contains(editor.Cues, c => c.Name == "Intro");
    }

    [Fact]
    public void CorrectingAnAutoDrop_ClearsTheOtherAutoCues()
    {
        var (editor, _) = Build(Stored(21, "Intro", type: CuePointType.Intro), Stored(65, "Drop 1"));
        editor.SelectedCue = editor.Cues.Single(c => c.Name == "Drop 1");

        editor.NudgeSelectedCommand.Execute("+bar").Subscribe();

        Assert.DoesNotContain(editor.Cues, c => c.Name == "Intro");
        Assert.Equal(67.0, editor.Cues.Single(c => c.Name == "Drop 1").Timestamp, 6);
    }

    [Fact]
    public void Keys1And2_PlaceDrop1AndDrop2_OnTheirPads()
    {
        var (editor, _) = Build();
        editor.InitDropCountdownMode(Singularity.Engine.Cueing.DropCountdownCues.DnB);

        editor.LastAuditionSeconds = 161;
        editor.SetNumberedDropHereCommand.Execute(2).Subscribe();
        editor.LastAuditionSeconds = 65;
        editor.SetNumberedDropHereCommand.Execute(1).Subscribe();

        Assert.Equal(new[] { ("[IN -16]", 0), ("[IN -8]", 1), ("[DROP 1]", 2), ("[IN -16]", 3), ("[IN -8]", 4), ("[DROP 2]", 5), ("[OUT]", 6) },
            editor.Cues.Select(c => (c.Name, c.SlotIndex)));
    }

    [Fact]
    public void AddingYourOwnCue_RemovesTheAutoCues()
    {
        var (editor, _) = Build(Stored(21, "Intro", type: CuePointType.Intro), Stored(65, "Drop 1"));

        editor.AddCueAtCommand.Execute(101.0).Subscribe();

        Assert.Equal(new[] { "Cue 3" }, editor.Cues.Select(c => c.Name));
        Assert.Contains("auto cues removed", editor.StatusText);
    }
}
