using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SLSKDONET.Data;
using SLSKDONET.Data.Entities;

namespace SLSKDONET.Services;

/// <summary>
/// Concrete implementation of ICuePointService backed by EF Core / SQLite.
/// </summary>
public class CuePointService : ICuePointService
{
    private readonly IDbContextFactory<AppDbContext> _dbFactory;
    private readonly ILogger<CuePointService> _logger;

    public CuePointService(IDbContextFactory<AppDbContext> dbFactory, ILogger<CuePointService> logger)
    {
        _dbFactory = dbFactory;
        _logger = logger;
    }

    /// <inheritdoc/>
    public async Task CreateManyAsync(IEnumerable<CuePointEntity> cuePoints, CancellationToken cancellationToken = default)
    {
        var list = cuePoints.ToList();
        if (list.Count == 0) return;

        await using var context = await _dbFactory.CreateDbContextAsync(cancellationToken);
        await context.CuePoints.AddRangeAsync(list, cancellationToken);
        await context.SaveChangesAsync(cancellationToken);

        _logger.LogDebug("Persisted {Count} cue points for track {Hash}", list.Count, list[0].TrackUniqueHash);
    }

    /// <inheritdoc/>
    public async Task<List<CuePointEntity>> GetByTrackIdAsync(string trackUniqueHash, CancellationToken cancellationToken = default)
    {
        await using var context = await _dbFactory.CreateDbContextAsync(cancellationToken);
        return await context.CuePoints
            .AsNoTracking()
            .Where(c => c.TrackUniqueHash == trackUniqueHash)
            .OrderBy(c => c.TimestampInSeconds)
            .ToListAsync(cancellationToken);
    }

    /// <inheritdoc/>
    public async Task DeleteAutoGeneratedByTrackIdAsync(string trackUniqueHash, CancellationToken cancellationToken = default)
    {
        await using var context = await _dbFactory.CreateDbContextAsync(cancellationToken);
        var toDelete = await context.CuePoints
            .Where(c => c.TrackUniqueHash == trackUniqueHash && c.IsAutoGenerated)
            .ToListAsync(cancellationToken);

        if (toDelete.Count == 0) return;

        context.CuePoints.RemoveRange(toDelete);
        await context.SaveChangesAsync(cancellationToken);

        _logger.LogDebug("Deleted {Count} auto-generated cue points for track {Hash}", toDelete.Count, trackUniqueHash);
    }

    /// <inheritdoc/>
    public async Task DeleteAllByTrackIdAsync(string trackUniqueHash, CancellationToken cancellationToken = default)
    {
        await using var context = await _dbFactory.CreateDbContextAsync(cancellationToken);
        var toDelete = await context.CuePoints
            .Where(c => c.TrackUniqueHash == trackUniqueHash)
            .ToListAsync(cancellationToken);

        if (toDelete.Count == 0) return;

        context.CuePoints.RemoveRange(toDelete);
        await context.SaveChangesAsync(cancellationToken);

        _logger.LogDebug("Deleted all {Count} cue points for track {Hash}", toDelete.Count, trackUniqueHash);
    }
}
