using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using SLSKDONET.Data.Entities;

namespace SLSKDONET.Services;

/// <summary>
/// Provides CRUD operations for auto-generated structural cue points.
/// </summary>
public interface ICuePointService
{
    /// <summary>
    /// Inserts a batch of cue points for a track, replacing any existing auto-generated ones first.
    /// </summary>
    Task CreateManyAsync(IEnumerable<CuePointEntity> cuePoints, CancellationToken cancellationToken = default);

    /// <summary>
    /// Returns all cue points associated with the given track hash, ordered by timestamp.
    /// </summary>
    Task<List<CuePointEntity>> GetByTrackIdAsync(string trackUniqueHash, CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes all auto-generated cue points for a track (useful before re-analysis).
    /// User-placed cue points (IsAutoGenerated = false) are preserved.
    /// </summary>
    Task DeleteAutoGeneratedByTrackIdAsync(string trackUniqueHash, CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes ALL cue points (both user-placed and auto-generated) for a track.
    /// </summary>
    Task DeleteAllByTrackIdAsync(string trackUniqueHash, CancellationToken cancellationToken = default);
}
