using System;
using System.Collections.Generic;
using System.Linq;
using Singularity.Data.Entities;

namespace Singularity.Engine.Analysis.CueDetr;

/// <summary>Where a track's auto cues come from.</summary>
public enum CueSourceMode
{
    /// <summary>ORBIT's own structure analysis only (the default).</summary>
    Orbit,
    /// <summary>ORBIT's cues, marked "✓AI" where CUE-DETR agrees, plus CUE-DETR's other points as
    /// cyan "AI" memory cues — both opinions side by side on the waveform.</summary>
    Compare,
    /// <summary>Only CUE-DETR's points (snapped to the bar grid), to judge the model on its own.</summary>
    AiOnly,
}

/// <summary>
/// Combines ORBIT's generated cues with CUE-DETR's points. On 68 tracks of hand-placed DJ cues,
/// ORBIT cues that CUE-DETR also found (within one bar) matched a DJ cue 52 % of the time, the rest
/// 23 % — agreement is a strong confidence signal, which Compare mode makes visible.
/// </summary>
public static class CueDetrFusion
{
    public const string AgreeSuffix = " ✓AI";
    public const string AiColour = "#00E5FF";
    private const double AgreeBars = 1.0;

    public static List<CuePointEntity> Apply(
        IReadOnlyList<CuePointEntity> orbitCues, IReadOnlyList<CueDetrPoint> ai,
        string trackHash, double bpm, double downbeat, double duration, CueSourceMode mode)
    {
        double bar = bpm > 0 ? 240.0 / bpm : 0;
        double Snap(double t) => bar <= 0 ? t : Math.Clamp(downbeat + Math.Round((t - downbeat) / bar) * bar, 0, Math.Max(0, duration));

        if (mode == CueSourceMode.Orbit) return orbitCues.ToList();

        var aiCues = new List<CuePointEntity>();
        if (mode == CueSourceMode.AiOnly)
        {
            int n = 0;
            foreach (var p in ai.OrderBy(p => p.Seconds))
            {
                double t = Snap(p.Seconds);
                if (aiCues.Any(c => Math.Abs(c.TimestampInSeconds - t) < 0.01)) continue;
                aiCues.Add(AiCue(trackHash, t, p.Score, $"AI {++n}"));
            }
            return aiCues;
        }

        // Compare
        double tolerance = bar > 0 ? AgreeBars * bar : 2.0;
        var result = new List<CuePointEntity>();
        foreach (var cue in orbitCues)
        {
            bool agreed = !cue.IsLoop && ai.Any(p => Math.Abs(p.Seconds - cue.TimestampInSeconds) <= tolerance);
            if (agreed)
            {
                cue.Label = (cue.Label ?? "") + AgreeSuffix;
                cue.Confidence = Math.Max(cue.Confidence, 0.9f);
            }
            result.Add(cue);
        }
        foreach (var p in ai.OrderBy(p => p.Seconds))
        {
            if (orbitCues.Any(c => Math.Abs(p.Seconds - c.TimestampInSeconds) <= tolerance)) continue;
            double t = Snap(p.Seconds);
            if (result.Any(c => Math.Abs(c.TimestampInSeconds - t) < 0.01)) continue;
            // Invariant: labels also end up in Rekordbox/Serato exports.
            result.Add(AiCue(trackHash, t, p.Score, FormattableString.Invariant($"AI {p.Score:0.00}")));
        }
        return result.OrderBy(c => c.TimestampInSeconds).ToList();
    }

    private static CuePointEntity AiCue(string hash, double t, double score, string label) => new()
    {
        TrackUniqueHash = hash,
        TimestampInSeconds = t,
        Type = CuePointType.PhraseBoundary,
        Label = label,
        Color = AiColour,
        IsAutoGenerated = true,
        Confidence = (float)Math.Clamp(score, 0, 1),
        SlotIndex = -1,
    };
}
