using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SLSKDONET.Data.Entities;

/// <summary>
/// Represents a persistent DJ cue point automatically detected via structural audio analysis.
/// Cue points can be of various types (intro, drop, build, etc.) and are associated with a track.
/// User-placed cue points are stored in OrbitCue (CuePointsJson); this entity tracks auto-generated ones.
/// </summary>
[Table("CuePoints")]
public class CuePointEntity
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Foreign key to the track via its unique content hash.
    /// </summary>
    [Required]
    public string TrackUniqueHash { get; set; } = string.Empty;

    /// <summary>
    /// Precise position within the track in seconds (high precision float).
    /// </summary>
    public double TimestampInSeconds { get; set; }

    /// <summary>
    /// Structural type of this cue point (Intro, Drop, Build, etc.)
    /// </summary>
    public CuePointType Type { get; set; }

    /// <summary>
    /// Human-readable label (e.g., "Drop 1", "Intro", "Build 1").
    /// </summary>
    [MaxLength(100)]
    public string Label { get; set; } = string.Empty;

    /// <summary>
    /// Display color as a hex string (e.g., "#FF0000" for red drops).
    /// Defaults are assigned by type during generation.
    /// </summary>
    [MaxLength(7)]
    public string Color { get; set; } = "#FFFFFF";

    /// <summary>
    /// True if this cue was created by the automated analysis engine.
    /// Auto-generated cues can be deleted and regenerated; user-placed cues (IsAutoGenerated=false) are preserved.
    /// </summary>
    public bool IsAutoGenerated { get; set; } = true;

    /// <summary>
    /// Confidence score (0.0 – 1.0) from the analysis heuristic.
    /// Low confidence cues may be flagged for review.
    /// </summary>
    public float Confidence { get; set; } = 1.0f;

    /// <summary>
    /// When this cue point was created.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// True when this cue is a loop (in+out point pair).
    /// </summary>
    public bool IsLoop { get; set; }

    /// <summary>
    /// Loop out point in seconds. Only meaningful when IsLoop is true.
    /// </summary>
    public double LoopEndSeconds { get; set; }

    /// <summary>
    /// Hot cue pad slot (0–7). -1 = memory cue (no pad). Defaults to -1.
    /// </summary>
    public int SlotIndex { get; set; } = -1;
}

/// <summary>
/// Types of structural cue points that the analysis engine can detect.
/// </summary>
public enum CuePointType
{
    /// <summary>Track introduction / opening section.</summary>
    Intro = 0,

    /// <summary>Track outro / closing section.</summary>
    Outro = 1,

    /// <summary>Main energy peak / "drop" moment (typically highest energy, kick+bass onset).</summary>
    Drop = 2,

    /// <summary>Low-energy breakdown or ambient section following the drop.</summary>
    Breakdown = 3,

    /// <summary>Build-up section leading into a drop.</summary>
    Build = 4,

    /// <summary>Detected structural phrase boundary (e.g., every 16/32 bars).</summary>
    PhraseBoundary = 5,
}
