using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Singularity.Data;
using Singularity.Views;

namespace Singularity.Services.AudioAnalysis;

/// <summary>
/// One-time, background re-fit of every already-analysed track's BPM, beat grid and downbeat with
/// <see cref="BeatGridFitter"/>, followed by a cues-only regeneration (auto cues only — user-placed
/// or user-edited cues are never touched). Works purely from stored data: the beat ticks in
/// <c>BeatGridJson</c> and the sub-bass structure events, so no audio is decoded. Where Rekordbox
/// has analysed the same audio, its own beat grid (with real downbeats) is used instead.
///
/// Why a one-off pass: tracks analysed before the fitter existed carry an integer/half-time-doubled
/// BPM (e.g. 178 for a real 174) that every cue gets snapped to. Re-analysing the whole library just
/// to fix that would take hours; this takes about a minute of background work.
///
/// Safety: a consistent SQLite backup of the library is written first (online backup API — a plain
/// file copy of a WAL-mode database isn't consistent), and a marker file makes the pass run once.
/// Displayed BPM keeps its existing precedence (manual edit and file tag still win) because the
/// write goes through <see cref="DatabaseService.UpdateAudioFeaturesAsync"/>.
/// </summary>
public sealed class BeatGridRecomputeService
{
    private const string PassName = "beatgrid-fit-v1";
    private static readonly TimeSpan StartDelay = TimeSpan.FromSeconds(60);

    private readonly ILogger<BeatGridRecomputeService> _logger;
    private readonly DatabaseService _database;
    private readonly AnalyzeTrackStructureJob _cueJob;
    private readonly IEventBus _eventBus;
    private readonly Rekordbox.IRekordboxPssiService? _rekordbox;

    public BeatGridRecomputeService(
        ILogger<BeatGridRecomputeService> logger,
        DatabaseService database,
        AnalyzeTrackStructureJob cueJob,
        IEventBus eventBus,
        Rekordbox.IRekordboxPssiService? rekordbox = null)
    {
        _rekordbox = rekordbox;
        _logger = logger;
        _database = database;
        _cueJob = cueJob;
        _eventBus = eventBus;
    }

    private static string OrbitDataDir =>
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Singularity");

    private static string MarkerPath => Path.Combine(OrbitDataDir, "Backups", $"{PassName}.done");

    /// <summary>Starts the pass in the background if it hasn't run yet. Never throws.</summary>
    public void StartIfPending(CancellationToken ct = default)
    {
        if (File.Exists(MarkerPath)) return;
        _ = Task.Run(async () =>
        {
            try
            {
                await Task.Delay(StartDelay, ct).ConfigureAwait(false); // stay clear of startup DB contention
                await RunAsync(ct).ConfigureAwait(false);
            }
            catch (OperationCanceledException) { }
            catch (Exception ex)
            {
                _logger.LogError(ex, "[BeatGridRecompute] Pass failed; it will retry on next launch.");
            }
        }, ct);
    }

    public async Task RunAsync(CancellationToken ct)
    {
        if (File.Exists(MarkerPath)) return;

        List<string> hashes;
        HashSet<string> hasAutoCues;
        var pathByHash = new Dictionary<string, string>();
        using (var db = new AppDbContext())
        {
            hashes = await db.AudioFeatures.AsNoTracking()
                .Where(f => f.Bpm > 0 && f.BeatGridJson != null && f.BeatGridJson.Length > 2)
                .Select(f => f.TrackUniqueHash)
                .ToListAsync(ct).ConfigureAwait(false);
            // Only tracks that already carry auto cues get them regenerated — a track whose auto
            // cues the user deleted must not have them come back.
            hasAutoCues = (await db.CuePoints.AsNoTracking()
                .Where(c => c.IsAutoGenerated)
                .Select(c => c.TrackUniqueHash)
                .Distinct()
                .ToListAsync(ct).ConfigureAwait(false)).ToHashSet();
            if (_rekordbox?.IsAvailable == true)
            {
                foreach (var e in await db.LibraryEntries.AsNoTracking()
                             .Where(e => e.FilePath != null && e.FilePath != "")
                             .Select(e => new { e.UniqueHash, e.FilePath })
                             .ToListAsync(ct).ConfigureAwait(false))
                    pathByHash.TryAdd(e.UniqueHash, e.FilePath!);
            }
        }
        if (hashes.Count == 0) { WriteMarker("no analysed tracks"); return; }

        string backup = BackupLibrary();
        _logger.LogInformation("[BeatGridRecompute] Re-fitting {Count} tracks (backup: {Backup})", hashes.Count, backup);

        int changed = 0, unchanged = 0, unfittable = 0, cueFailures = 0, fromRekordbox = 0;
        var started = DateTime.UtcNow;
        for (int i = 0; i < hashes.Count; i++)
        {
            ct.ThrowIfCancellationRequested();
            var features = await _database.GetAudioFeaturesByHashAsync(hashes[i]).ConfigureAwait(false);
            if (features is null) continue;

            float oldBpm = features.Bpm;
            double oldAnchor = features.DownbeatOffsetSeconds;
            var ticks = BeatGridFitter.ParseTicks(features.BeatGridJson);
            bool fitted = BeatGridFitter.ApplyTo(features, ticks, BeatGridFitter.StructuralEventsFrom(features));

            // Rekordbox's own grid wins where it has analysed the same audio (see ApplyRekordboxGrid).
            if (_rekordbox is not null && pathByHash.TryGetValue(features.TrackUniqueHash, out var file)
                && await _rekordbox.GetBeatGridAsync(file, ct).ConfigureAwait(false) is { } rbGrid
                && BeatGridFitter.ApplyRekordboxGrid(features, rbGrid, ticks))
            {
                fitted = true;
                fromRekordbox++;
            }

            if (!fitted)
            {
                unfittable++;
                continue;
            }
            if (Math.Abs(features.Bpm - oldBpm) < 0.005 && Math.Abs(features.DownbeatOffsetSeconds - oldAnchor) < 0.001)
            {
                unchanged++;
                continue;
            }

            await _database.UpdateAudioFeaturesAsync(features).ConfigureAwait(false);
            if (hasAutoCues.Contains(features.TrackUniqueHash) &&
                !await _cueJob.RegenerateCuesOnlyAsync(features.TrackUniqueHash, ct).ConfigureAwait(false))
                cueFailures++;
            changed++;

            if ((i + 1) % 250 == 0)
            {
                _logger.LogInformation("[BeatGridRecompute] {Done}/{Total} ({Changed} updated)", i + 1, hashes.Count, changed);
                await Task.Delay(50, ct).ConfigureAwait(false); // let foreground writers in
            }
        }

        string summary = $"{changed} updated ({fromRekordbox} from Rekordbox's own grid), {unchanged} already correct, {unfittable} kept (no steady tempo), " +
                         $"{cueFailures} cue regenerations failed, {(DateTime.UtcNow - started).TotalSeconds:F0}s";
        _logger.LogInformation("[BeatGridRecompute] Done: {Summary}", summary);
        WriteMarker(summary);

        if (changed > 0)
            _eventBus.Publish(new ToastRequestedEvent(
                "Beat grids updated",
                $"Re-fitted BPM and beat grid for {changed} tracks and refreshed their auto cues. Your own cues were not changed.",
                NotificationType.Success, TimeSpan.FromSeconds(8)));
    }

    private string BackupLibrary()
    {
        string source = Singularity.Data.OrbitPaths.LibraryDbPath;
        string dir = Path.Combine(OrbitDataDir, "Backups");
        Directory.CreateDirectory(dir);
        string target = Path.Combine(dir, $"library.db.bak-{PassName}-{DateTime.Now:yyyyMMdd-HHmmss}");

        using var src = new SqliteConnection(new SqliteConnectionStringBuilder { DataSource = source, Mode = SqliteOpenMode.ReadOnly }.ToString());
        using var dst = new SqliteConnection(new SqliteConnectionStringBuilder { DataSource = target }.ToString());
        src.Open();
        dst.Open();
        src.BackupDatabase(dst);
        SqliteConnection.ClearPool(dst); // release the backup file handle
        return target;
    }

    private void WriteMarker(string summary)
    {
        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(MarkerPath)!);
            File.WriteAllText(MarkerPath, $"{DateTime.UtcNow:O}\n{summary}\n");
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "[BeatGridRecompute] Could not write marker {Path}", MarkerPath);
        }
    }
}
