using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SLSKDONET.Data;
using SLSKDONET.Engine.Analysis.CueDetr;

namespace SLSKDONET.Services.AudioAnalysis;

public sealed record CueDetrRegenResult(bool Success, int CueCount, int AiPoints, int Agreed, bool RanModel, string? Error = null);

/// <summary>
/// Regenerates a track's auto cues with CUE-DETR in the loop (see <see cref="CueSourceMode"/>).
/// CUE-DETR's points are computed once per track and model (~10 s) and cached in
/// audio_features.CueDetrJson, so switching modes afterwards is instant. Hand-placed cues are
/// never touched — only IsAutoGenerated cues are replaced.
/// </summary>
public sealed class CueDetrCueService
{
    private readonly DatabaseService _database;
    private readonly Engine.Cueing.CueGenerationService _generator;
    private readonly CueDetrService _cueDetr;
    private readonly IDbContextFactory<AppDbContext> _contextFactory;
    private readonly ILogger<CueDetrCueService> _logger;

    public CueDetrCueService(DatabaseService database, Engine.Cueing.CueGenerationService generator, CueDetrService cueDetr,
        IDbContextFactory<AppDbContext> contextFactory, ILogger<CueDetrCueService> logger)
    {
        _database = database;
        _generator = generator;
        _cueDetr = cueDetr;
        _contextFactory = contextFactory;
        _logger = logger;
    }

    public bool IsModelAvailable => _cueDetr.IsAvailable;

    public async Task<CueDetrRegenResult> RegenerateAsync(string trackHash, string? filePath, CueSourceMode mode, CancellationToken ct = default)
    {
        var features = await _database.GetAudioFeaturesByHashAsync(trackHash).ConfigureAwait(false);
        if (features == null || features.Bpm <= 0 || features.TrackDuration <= 0)
            return new(false, 0, 0, 0, false, "not analysed yet");

        List<CueDetrPoint> points = new();
        bool ran = false;
        if (mode != CueSourceMode.Orbit)
        {
            var cached = ReadCache(features.CueDetrJson, _cueDetr.ModelTag);
            if (cached != null) points = cached;
            else
            {
                if (!_cueDetr.IsAvailable) return new(false, 0, 0, 0, false, "CUE-DETR model not installed");
                if (string.IsNullOrEmpty(filePath) || !File.Exists(filePath)) return new(false, 0, 0, 0, false, "file missing");
                var detected = await _cueDetr.DetectFileAsync(filePath, ct).ConfigureAwait(false);
                if (detected == null) return new(false, 0, 0, 0, false, "CUE-DETR couldn't read the audio");
                points = detected;
                ran = true;
                await SaveCacheAsync(trackHash, points, ct).ConfigureAwait(false);
            }
        }

        var analysis = Engine.Analysis.AnalysisPipelineResultBuilder.Build(features);
        double anchor = features.DownbeatOffsetSeconds > 0 ? features.DownbeatOffsetSeconds : 0.0;
        var orbit = _generator.GenerateCues(trackHash, analysis, anchor,
            features.VocalStartSeconds, features.VocalEndSeconds,
            features.VocalIntensity > 0 ? features.VocalIntensity : null);
        var cues = CueDetrFusion.Apply(orbit, points, trackHash, features.Bpm, anchor, features.TrackDuration, mode);
        await _generator.ReplaceAutoCuesAsync(trackHash, cues, ct).ConfigureAwait(false);

        int agreed = cues.Count(c => c.Label.EndsWith(CueDetrFusion.AgreeSuffix, StringComparison.Ordinal));
        _logger.LogInformation("[CueDetr] {Hash}: {Mode} → {Cues} cues ({Ai} AI points, {Agreed} agreed{Ran})",
            trackHash, mode, cues.Count, points.Count, agreed, ran ? ", model run" : ", cached");
        return new(true, cues.Count, points.Count, agreed, ran);
    }

    private sealed record CachePoint(double t, double s);
    private sealed record Cache(string? model, List<CachePoint> points);

    /// <summary>Cached points, or null when missing or produced by a different model file.</summary>
    internal static List<CueDetrPoint>? ReadCache(string? json, string? modelTag)
    {
        if (string.IsNullOrWhiteSpace(json)) return null;
        try
        {
            var cache = JsonSerializer.Deserialize<Cache>(json);
            if (cache?.points == null || (modelTag != null && cache.model != modelTag)) return null;
            return cache.points.Select(p => new CueDetrPoint(
                (int)Math.Round(p.t * CueDetrFrontEnd.SampleRate / CueDetrFrontEnd.Hop), p.t, p.s)).ToList();
        }
        catch (JsonException) { return null; }
    }

    private async Task SaveCacheAsync(string trackHash, List<CueDetrPoint> points, CancellationToken ct)
    {
        var json = JsonSerializer.Serialize(new Cache(_cueDetr.ModelTag,
            points.Select(p => new CachePoint(Math.Round(p.Seconds, 3), Math.Round(p.Score, 4))).ToList()));
        using var db = await _contextFactory.CreateDbContextAsync(ct).ConfigureAwait(false);
        await db.AudioFeatures.Where(f => f.TrackUniqueHash == trackHash)
            .ExecuteUpdateAsync(s => s.SetProperty(f => f.CueDetrJson, json), ct).ConfigureAwait(false);
    }
}
