using System;
using SLSKDONET.Data.Entities;

namespace SLSKDONET.Models;

/// <summary>
/// Source of a cue point.
/// </summary>
public enum CueSource
{
    Auto,  // Generated by ML/Heuristics
    User   // Manually placed or adjusted by user
}

/// <summary>
/// Professional role/label for a cue point.
/// </summary>
public enum CueRole
{
    Intro,
    KickIn,
    Breakdown,
    Breakdown2,
    Drop,
    Climax,
    Vocals,
    Outro,
    Bridge,
    Build,
    PhraseStart,
    Custom
}

/// <summary>
/// Represents a surgical cue point for DJ preparation.
/// part of the Phase 10 Interactive Cue Ecosystem.
/// </summary>
public class OrbitCue
{
    /// <summary>
    /// Position in seconds.
    /// </summary>
    public double Timestamp { get; set; }

    /// <summary>
    /// Human-readable name.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Hex color code for DJ hardware (e.g., #FF0000 for Red/Drop).
    /// </summary>
    public string Color { get; set; } = "#FFFFFF";

    /// <summary>
    /// Whether this was generated by ORBIT or placed by the user.
    /// User cues are NEVER overwritten by auto-analysis.
    /// </summary>
    public CueSource Source { get; set; } = CueSource.Auto;

    /// <summary>
    /// Confidence score (0.0 - 1.0) based on transient alignment.
    /// Low confidence cues are flagged for "Review" in the UI.
    /// </summary>
    public double Confidence { get; set; } = 1.0;

    /// <summary>
    /// The structural role of this cue.
    /// </summary>
    public CueRole Role { get; set; } = CueRole.Custom;
    
    /// <summary>
    /// Optional slot index for hardware mapping (Hot Cue 1-8).
    /// </summary>
    public int SlotIndex { get; set; }

    /// <summary>
    /// When true, this cue represents a loop. LoopEndSeconds marks the loop out point.
    /// </summary>
    public bool IsLoop { get; set; }

    /// <summary>
    /// Loop end position in seconds. Only meaningful when IsLoop is true.
    /// </summary>
    public double LoopEndSeconds { get; set; }

    /// <summary>
    /// True when this is the specific cue TransitionEngine.OptimizeTransition picked as its
    /// mix-out/mix-in recommendation (Mix transition editor). Set once when the suggestion is
    /// computed and left alone after — it represents what the algorithm originally recommended,
    /// distinct from wherever the live trigger point (Nudge, a different cue click) currently
    /// sits, which a waveform's own playhead/progress marker already shows.
    /// </summary>
    public bool IsSuggested { get; set; }

    // ── Display helpers (derived, not persisted) ───────────────────────────

    public string TimestampDisplay => TimeSpan.FromSeconds(Timestamp).ToString(@"mm\:ss\.ff");
    public bool HasSlot => SlotIndex >= 0;
    public string SlotLabel => SlotIndex >= 0 ? ((char)('A' + Math.Min(SlotIndex, 7))).ToString() : string.Empty;

    // Confidence colour: green ≥80%, amber ≥50%, red <50%
    public string ConfidenceColor => Confidence >= 0.8 ? "#44DD88" : Confidence >= 0.5 ? "#FF9800" : "#FF5555";

    /// <summary>Read-only mapping from the persisted <see cref="CuePointEntity"/> to this display
    /// model — same shape as CueForgeViewModel's private EntityToOrbitCue, shared here so other
    /// consumers (e.g. MixTransitionViewModel's cue-picker waveforms) that only need to DISPLAY
    /// cues, not edit/persist them, don't have to duplicate the mapping.</summary>
    public static OrbitCue FromEntity(CuePointEntity e) => new()
    {
        Timestamp = e.TimestampInSeconds,
        Name = e.Label,
        Color = e.Color,
        Source = e.IsAutoGenerated ? CueSource.Auto : CueSource.User,
        Role = e.Type switch
        {
            CuePointType.Intro => CueRole.Intro,
            CuePointType.Outro => CueRole.Outro,
            CuePointType.Drop => CueRole.Drop,
            CuePointType.Breakdown => CueRole.Breakdown,
            CuePointType.Build => CueRole.Build,
            CuePointType.PhraseBoundary => CueRole.PhraseStart,
            _ => CueRole.Custom,
        },
        Confidence = e.Confidence,
        IsLoop = e.IsLoop,
        LoopEndSeconds = e.LoopEndSeconds,
        SlotIndex = e.SlotIndex,
    };

    /// <summary>Inverse of <see cref="FromEntity"/> — the persisted shape both cue editors (Cue Forge
    /// and the Flow Builder transition editor) write back.</summary>
    public CuePointEntity ToEntity(string trackHash) => new()
    {
        Id = Guid.NewGuid(),
        TrackUniqueHash = trackHash,
        TimestampInSeconds = Timestamp,
        Label = Name,
        Color = Color,
        IsAutoGenerated = Source == CueSource.Auto,
        Type = Role switch
        {
            CueRole.Intro => CuePointType.Intro,
            CueRole.Outro => CuePointType.Outro,
            CueRole.Drop => CuePointType.Drop,
            CueRole.Breakdown or CueRole.Breakdown2 => CuePointType.Breakdown,
            CueRole.Build => CuePointType.Build,
            _ => CuePointType.PhraseBoundary,
        },
        Confidence = (float)Confidence,
        IsLoop = IsLoop,
        LoopEndSeconds = LoopEndSeconds,
        SlotIndex = SlotIndex,
        CreatedAt = DateTime.UtcNow,
    };

    /// <summary>Field-for-field copy — undo snapshots need cues that later edits can't mutate.</summary>
    public OrbitCue Clone() => (OrbitCue)MemberwiseClone();

    // "Why here?" one-liner shown as tooltip on the confidence dot
    public string WhyHereTooltip
    {
        get
        {
            string src = Source == CueSource.User ? "User cue" : $"Auto — {Role}";
            string conf = Source == CueSource.Auto ? $" ({(int)(Confidence * 100)}% confidence)" : "";
            string bar = Timestamp > 0 ? $" @ {TimestampDisplay}" : "";
            return $"{src}{conf}{bar}";
        }
    }
}
